const genSeats = [
  { seat: "W1", index: 1 },
  { seat: "P2", index: 2 },
  { seat: "P3", index: 3 },
  { seat: "W4", index: 4 },
  { seat: "W5", index: 5 },
  { seat: "P6", index: 6 },
  { seat: "P7", index: 7 },
  { seat: "W8", index: 8 },
  { seat: "W9", index: 9 },
  { seat: "P10", index: 10 },
  { seat: "P11", index: 11 },
  { seat: "W12", index: 12 },
  { seat: "W13", index: 13 },
  { seat: "P14", index: 14 },
  { seat: "P15", index: 15 },
  { seat: "W16", index: 16 },
  { seat: "W17", index: 17 },
  { seat: "P18", index: 18 },
  { seat: "P19", index: 19 },
  { seat: "W20", index: 20 },
  { seat: "W21", index: 21 },
  { seat: "P22", index: 22 },
  { seat: "P23", index: 23 },
  { seat: "W24", index: 24 },
  { seat: "W25", index: 25 },
  { seat: "P26", index: 26 },
  { seat: "P27", index: 27 },
  { seat: "W28", index: 28 },
  { seat: "W29", index: 29 },
  { seat: "P30", index: 30 },
  { seat: "P31", index: 31 },
  { seat: "W32", index: 32 },
];

const sleSeats = [
  { seat: "U1", index: 1 },
  { seat: "D2", index: 2 },
  { seat: "U3", index: 3 },
  { seat: "D4", index: 4 },
  { seat: "U5", index: 5 },
  { seat: "D6", index: 6 },
  { seat: "U7", index: 7 },
  { seat: "D8", index: 8 },
  { seat: "U9", index: 9 },
  { seat: "D10", index: 10 },
  { seat: "U11", index: 11 },
  { seat: "D12", index: 12 },
  { seat: "U13", index: 13 },
  { seat: "D14", index: 14 },
  { seat: "U15", index: 15 },
  { seat: "D16", index: 16 },
];
const scheduleTable = [
  {
    type: "Shovon",
    seats: 32,
    couches: 6,
    seatList: genSeats,
  },
  {
    type: "Snigdha",
    seats: 32,
    couches: 3,
    seatList: genSeats,
  },
  {
    type: "Sleeper",
    seats: 16,
    couches: 2,
    seatList: sleSeats,
  },
];
export { genSeats, sleSeats, scheduleTable };
